# Generated by Django 3.0.5 on 2023-10-25 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20231019_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='exam.Course'),
        ),
    ]
